FROM node:20 as builder

WORKDIR /build

COPY package*.json .

COPY src/ src/
COPY tsconfig.json tsconfig.json

RUN npm install

COPY public/temp public/temp

RUN npm run build

FROM node:20 as runner

WORKDIR /app

COPY --from=builder build/package*.json .
COPY --from=builder build/node_modules node_modules
COPY --from=builder build/public/temp public/temp
COPY --from=builder build/dist dist/

CMD [ "npm", "start" ]